#!/bin/sh

ln -s $PWD/.zshrc $HOME/.zshrc
ln -s $PWD/.vimrc $HOME/.vimrc
ln -s $PWD/.gitconfig $HOME/.gitconfig
ln -s $PWD/.tmux.conf $HOME/.tmux.conf

brew install romkatv/powerlevel10k/powerlevel10k
brew install diff-so-fancy
brew install zsh-syntax-highlighting
brew install z
