#!/bin/sh

ln -s $PWD/.zshrc $HOME/.zshrc
ln -s $PWD/.vimrc $HOME/.vimrc
ln -s $PWD/.gitconfig $HOME/.gitconfig
ln -s $PWD/.tmux.conf $HOME/.tmux.conf

git submodule init && git submodule update
npm install -g pure-prompt
brew install diff-so-fancy
